#!/usr/bin/env python

from translate import translate
import argparse
import sys
import time

parser = argparse.ArgumentParser()
parser.add_argument('infile', help='file to translate')
parser.add_argument('outfile', help='file to write output to')
parser.add_argument('src', help='Source language')
parser.add_argument('tgt', help='Target language')
args = parser.parse_args()

bag = set()
for line in open(args.infile):
    words = line.strip().split()
    for word in words:
        bag.add(word)

ptr = open(args.outfile, 'w')
counter = 0
for word in sorted(bag):
    counter += 1
    #if counter % 20 == 0: sys.stderr.write('.')
    sys.stderr.write('Translating ' + word + '\n')
    for translation in translate(word, args.src, args.tgt):
        ptr.write(word + '|' + translation + '\n')
        sys.stderr.write(word + '|' + translation + '\n')
    # be nice to wikipedia
    time.sleep(1.0)
ptr.close()
sys.stderr.write('\n')
